version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8002:80
        depends_on:
            - app
        container_name: test_vyyer_nginx

    app:
        build:
            context: .
            dockerfile: ./_docker/php/Dockerfile
        volumes:
            - ./:/var/www
        container_name: test_vyyer_app
